name: Build and Release FreeFeta

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35           # matches compileSdk
          build-tools: 35.0.0     # must match compileSdk (or higher)
          cmake: false
          ndk: false

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleProductionRelease

      - name: Sign APK
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/production/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "35.0.0"
          
      - name: Rename signed APK
        id: rename
        run: |
          # Extract version from tag
          VERSION=${GITHUB_REF#refs/tags/}
          SIGNED_APK=$(ls app/build/outputs/apk/production/release/*-signed.apk)
          mv "$SIGNED_APK" "app/build/outputs/apk/production/release/FreeFeta-$VERSION.apk"
        shell: bash

      - name: Upload release APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: FreeFeta-Release
          path: app/build/outputs/apk/production/release/FreeFeta-*.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/production/release/FreeFeta-*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

